###
POST http://localhost:9000/api/noticias HTTP/1.1
Content-Type: application/json: 
{
    "tituloNoticia":"Ya no quiero hacer nadaaaaaaaaa",
    "tipoNoticia":"Espectaculo",
    "fechaPub":"01 de mayo 2023",
    "autor":"Anonymuu",
    "parrafoPrincipal":"1 2 3 4 5, ya no se que mas escribir.",
    "contenidoNoticia":"6 7 8 9 10, ya vamonos."

}

###
GET http://localhost:9000/api/noticias HTTP/1.1

###
GET http://localhost:9000/api/noticias/6465cba3229f74b5277cb2cb HTTP/1.1

###
PUT http://localhost:9000/api/noticias/6465cba3229f74b5277cb2cb HTTP/1.1
Content-Type: application/json: 

{
    "tituloNoticia":"Ya no quiero hacer nadaaaaaaaaa",
    "tipoNoticia":"Espectaculo",
    "fechaPub":"01 de mayo 2023",
    "autor":"A",
    "parrafoPrincipal":"1 2 3 4 5, ya no se que mas escribir.",
    "contenidoNoticia":"6 7 8 9 10, ya vamonos."

}